import type { BuiltinIcon } from "./types";

/**
 * Curated built-in icon registry. ⭐ First-party, generic *function* glyphs only —
 * NOT third-party brand logos (licensing/safety deferred; see ADR 0014). Each
 * glyph is a monochrome SVG in public/icons/builtin/ rendered with currentColor so
 * it adapts to the theme. `aliases` drive name→icon suggestion (suggest.ts).
 *
 * v0.2.7 (Icon Alias Expansion & Generic Icon Set) grew this from the original 16
 * keys to ~30 by adding generic keys for large, previously-uncovered app classes
 * (ai, proxy, identity, automation, camera, backup, notes, finance, rss, server,
 * indexer, calendar, search, requests) and expanding aliases across the board.
 *
 * Alias rules (enforced by review, not code): all aliases are normalized lowercase
 * alphanumeric; avoid aliases < 3 chars unless they are exact-match safe (a 1–2
 * char alias only ever matches an app whose normalized name equals it). Each alias
 * lives on exactly ONE key — duplicates would tie and resolve by registry order.
 */
export const BUILTIN_ICONS: readonly BuiltinIcon[] = [
  // --- original keys (v0.2.6), aliases expanded in v0.2.7 --------------------
  {
    key: "media",
    label: "Media",
    file: "media.svg",
    monochrome: true,
    aliases: [
      "plex",
      "plexmediaserver",
      "pms",
      "jellyfin",
      "emby",
      "embyserver",
      "tv",
      "movies",
      "video",
      "kodi",
      "xbmc",
      "stream",
      "sonarr",
      "radarr",
      "whisparr",
      "bazarr",
      "tdarr",
      "unmanic",
      "fileflows",
      "streama",
      "stash",
      "tautulli",
      "plexpy",
      "iptv",
      "dvr",
      "subtitles",
      "tubearchivist",
      "watcharr",
      "ersatztv",
      "threadfin",
      "xteve",
    ],
  },
  {
    key: "download",
    label: "Downloads",
    file: "download.svg",
    monochrome: true,
    aliases: [
      "qbittorrent",
      "qbit",
      "transmission",
      "sabnzbd",
      "sab",
      "sabnzbdplus",
      "nzbget",
      "nzb",
      "deluge",
      "torrent",
      "download",
      "aria2",
      "ariang",
      "rtorrent",
      "rutorrent",
      "flood",
      "jdownloader",
      "pyload",
      "metube",
      "ytdlp",
      "youtubedl",
      "autobrr",
      "unpackerr",
      "slskd",
      "soulseek",
      "crossseed",
      "pinchflat",
      "biglybt",
      "vuze",
      "debrid",
      "rdtclient",
    ],
  },
  {
    key: "book",
    label: "Books / Wiki",
    file: "book.svg",
    monochrome: true,
    aliases: [
      "calibre",
      "calibreweb",
      "audiobookshelf",
      "readarr",
      "kavita",
      "komga",
      "books",
      "library",
      "ebook",
      "wiki",
      "wikijs",
      "bookstack",
      "knowledgebase",
      "documentation",
      "mediawiki",
      "outline",
    ],
  },
  {
    key: "shield",
    label: "Network / Security",
    file: "shield.svg",
    monochrome: true,
    aliases: [
      "pihole",
      "adguard",
      "adguardhome",
      "firewall",
      "vpn",
      "wireguard",
      "wgeasy",
      "tailscale",
      "headscale",
      "openvpn",
      "zerotier",
      "netbird",
      "security",
      "shield",
      "adblock",
      "dns",
      "opnsense",
      "pfsense",
      "network",
      "technitium",
      "unbound",
      "blocky",
      "dnsmasq",
      "openwrt",
      "router",
      "mikrotik",
      "routeros",
      "pfblockerng",
      "crowdsec",
      "fail2ban",
      "flaresolverr",
      "gluetun",
      "ddns",
    ],
  },
  {
    key: "chart",
    label: "Metrics",
    file: "chart.svg",
    monochrome: true,
    aliases: [
      "grafana",
      "prometheus",
      "prom",
      "metrics",
      "tsdb",
      "timeseries",
      "observability",
      "dashboards",
      "graph",
      "analytics",
      "loki",
      "telemetry",
      "statistics",
      "stats",
      "speedtest",
      "speedtesttracker",
      "librespeed",
      "emoncms",
      "solar",
      "energy",
      "growatt",
    ],
  },
  {
    key: "database",
    label: "Database",
    file: "database.svg",
    monochrome: true,
    aliases: [
      "postgres",
      "postgresql",
      "pgsql",
      "mysql",
      "mariadb",
      "redis",
      "valkey",
      "mongo",
      "mongodb",
      "database",
      "sqlite",
      "influxdb",
      "influx",
      "pgadmin",
      "phpmyadmin",
      "adminer",
      "rediscommander",
      "cloudbeaver",
      "dbeaver",
      "nosql",
      "couchdb",
      "cassandra",
    ],
  },
  {
    key: "container",
    label: "Containers",
    file: "container.svg",
    monochrome: true,
    aliases: [
      "portainer",
      "docker",
      "kubernetes",
      "k8s",
      "container",
      "yacht",
      "dockge",
      "compose",
      "registry",
      "watchtower",
      "komodo",
      "rancher",
      "swarm",
      "coolify",
      "dokploy",
      "caprover",
      "dokku",
      "paas",
      "deploy",
      "dozzle",
      "cadvisor",
    ],
  },
  {
    key: "home",
    label: "Home / Dashboard",
    file: "home.svg",
    monochrome: true,
    aliases: [
      "home",
      "homeassistant",
      "hass",
      "haos",
      "dashboard",
      "homepage",
      "homarr",
      "heimdall",
      "house",
      "dashy",
      "flame",
      "organizr",
      "glance",
    ],
  },
  {
    key: "cloud",
    label: "Cloud / Sync",
    file: "cloud.svg",
    monochrome: true,
    aliases: [
      "nextcloud",
      "owncloud",
      "cloud",
      "seafile",
      "syncthing",
      "drive",
      "sync",
      "filesync",
      "resilio",
      "rclone",
      "pydio",
      "filerun",
    ],
  },
  {
    key: "storage",
    label: "Storage / NAS",
    file: "storage.svg",
    monochrome: true,
    aliases: [
      "nas",
      "truenas",
      "unraid",
      "storage",
      "minio",
      "disk",
      "samba",
      "smb",
      "files",
      "filebrowser",
      "openmediavault",
      "omv",
      "s3",
      "objectstorage",
      "garage",
      "sftpgo",
      "sftp",
      "filestash",
      "webdav",
      "fileserver",
    ],
  },
  {
    key: "code",
    label: "Code / Git",
    file: "code.svg",
    monochrome: true,
    aliases: [
      "gitea",
      "gitlab",
      "github",
      "git",
      "code",
      "vscode",
      "vscodeserver",
      "codeserver",
      "forgejo",
      "jenkins",
      "drone",
      "woodpecker",
      "cicd",
      "pipeline",
      "ide",
      "editor",
      "coder",
      "sonarqube",
      "verdaccio",
      "gitserver",
      "forge",
      "repos",
      "recyclarr",
      "configarr",
      "buildarr",
    ],
  },
  {
    key: "mail",
    label: "Mail",
    file: "mail.svg",
    monochrome: true,
    aliases: [
      "mail",
      "mailcow",
      "roundcube",
      "email",
      "smtp",
      "postfix",
      "imap",
      "dovecot",
      "mailu",
      "snappymail",
      "stalwart",
    ],
  },
  {
    key: "music",
    label: "Music",
    file: "music.svg",
    monochrome: true,
    aliases: [
      "navidrome",
      "lidarr",
      "music",
      "airsonic",
      "plexamp",
      "funkwhale",
      "audio",
      "subsonic",
      "gonic",
      "mopidy",
      "polaris",
      "ampache",
    ],
  },
  {
    key: "photo",
    label: "Photos",
    file: "photo.svg",
    monochrome: true,
    aliases: [
      "immich",
      "photoprism",
      "photo",
      "photos",
      "piwigo",
      "lychee",
      "gallery",
      "image",
      "librephotos",
      "chevereto",
    ],
  },
  {
    key: "monitor",
    label: "Monitoring",
    file: "monitor.svg",
    monochrome: true,
    aliases: [
      "monitor",
      "glances",
      "scrutiny",
      "librenms",
      "zabbix",
      "status",
      "healthchecks",
      "healthcheck",
      "gotify",
      "ntfy",
      "apprise",
      "uptime",
      "uptimekuma",
      "kuma",
      "netdata",
      "monitoring",
      "beszel",
      "checkmk",
      "smokeping",
      "graylog",
      "gatus",
      "statping",
      "ntopng",
      "netalertx",
      "observium",
    ],
  },
  {
    key: "generic",
    label: "Generic App",
    file: "generic.svg",
    monochrome: true,
    aliases: [
      "app",
      "application",
      "generic",
      "misc",
      "other",
      "tools",
      "utility",
      "custom",
      "link",
    ],
  },

  // --- v0.2.7 new keys (Tier 1) ----------------------------------------------
  {
    key: "ai",
    label: "AI / LLM",
    file: "ai.svg",
    monochrome: true,
    aliases: [
      "ai",
      "llm",
      "localllm",
      "ollama",
      "openwebui",
      "ollamaui",
      "lmstudio",
      "localai",
      "librechat",
      "anythingllm",
      "oobabooga",
      "textgenwebui",
      "textgenerationwebui",
      "gpt4all",
      "gpt",
      "llamacpp",
      "llamafile",
      "comfyui",
      "stablediffusion",
      "automatic1111",
      "a1111",
      "sdwebui",
      "invokeai",
      "fooocus",
      "whisper",
      "whispercpp",
      "piper",
      "vllm",
      "flowise",
      "dify",
      "perplexica",
      "koboldcpp",
      "janai",
      "inference",
      "neural",
      "chatbot",
    ],
  },
  {
    key: "proxy",
    label: "Reverse Proxy",
    file: "proxy.svg",
    monochrome: true,
    aliases: [
      "traefik",
      "nginxproxymanager",
      "proxymanager",
      "nginx",
      "caddy",
      "caddyserver",
      "haproxy",
      "swag",
      "zoraxy",
      "pangolin",
      "reverseproxy",
      "ingress",
      "proxy",
      "loadbalancer",
      "nginxui",
      "npmplus",
    ],
  },
  {
    key: "identity",
    label: "Identity / Secrets",
    file: "identity.svg",
    monochrome: true,
    aliases: [
      "authelia",
      "authentik",
      "keycloak",
      "vaultwarden",
      "bitwarden",
      "vault",
      "hashicorpvault",
      "infisical",
      "lldap",
      "openldap",
      "freeipa",
      "zitadel",
      "pocketid",
      "oauth2proxy",
      "sso",
      "oidc",
      "ldap",
      "identity",
      "passbolt",
      "keepass",
      "keepassxc",
      "secrets",
      "secretsmanager",
      "credentials",
      "passwords",
      "passwordmanager",
      "authentication",
      "certbot",
      "letsencrypt",
      "stepca",
    ],
  },
  {
    key: "automation",
    label: "Automation",
    file: "automation.svg",
    monochrome: true,
    aliases: [
      "nodered",
      "esphome",
      "esp32",
      "esp8266",
      "zigbee2mqtt",
      "zigbee",
      "z2m",
      "zwave",
      "zwavejs",
      "zwavejsui",
      "mqtt",
      "mosquitto",
      "openhab",
      "domoticz",
      "homebridge",
      "homekit",
      "tasmota",
      "automation",
      "iot",
      "smarthome",
      "hacs",
      "evcc",
      "wled",
    ],
  },
  {
    key: "camera",
    label: "Camera / NVR",
    file: "camera.svg",
    monochrome: true,
    aliases: [
      "frigate",
      "scrypted",
      "motioneye",
      "zoneminder",
      "shinobi",
      "viseron",
      "agentdvr",
      "ispy",
      "blueiris",
      "go2rtc",
      "nvr",
      "cctv",
      "camera",
      "surveillance",
      "webrtc",
      "rtsp",
    ],
  },
  {
    key: "backup",
    label: "Backup",
    file: "backup.svg",
    monochrome: true,
    aliases: [
      "duplicati",
      "restic",
      "kopia",
      "borg",
      "borgbackup",
      "borgmatic",
      "urbackup",
      "vorta",
      "duplicacy",
      "backrest",
      "backup",
      "restore",
      "snapshot",
      "snapshots",
      "proxmoxbackup",
      "pbs",
    ],
  },
  {
    key: "notes",
    label: "Notes",
    file: "notes.svg",
    monochrome: true,
    aliases: [
      "trilium",
      "triliumnext",
      "joplin",
      "memos",
      "docmost",
      "affine",
      "appflowy",
      "obsidian",
      "silverbullet",
      "hedgedoc",
      "notes",
      "notetaking",
      "pkm",
      "standardnotes",
      "anytype",
      "notesnook",
    ],
  },
  {
    key: "finance",
    label: "Finance",
    file: "finance.svg",
    monochrome: true,
    aliases: [
      "fireflyiii",
      "firefly",
      "actual",
      "actualbudget",
      "ghostfolio",
      "maybefinance",
      "ezbookkeeping",
      "wallos",
      "finance",
      "budget",
      "money",
      "accounting",
      "invoice",
      "invoiceninja",
      "expense",
      "networth",
      "portfolio",
    ],
  },
  {
    key: "rss",
    label: "RSS / Feeds",
    file: "rss.svg",
    monochrome: true,
    aliases: [
      "freshrss",
      "miniflux",
      "ttrss",
      "tinytinyrss",
      "commafeed",
      "newsblur",
      "wallabag",
      "readeck",
      "omnivore",
      "rss",
      "feeds",
      "feed",
      "feedreader",
      "news",
      "atom",
      "readitlater",
    ],
  },
  {
    key: "server",
    label: "Server / Virtualization",
    file: "server.svg",
    monochrome: true,
    aliases: [
      "proxmox",
      "pve",
      "cockpit",
      "webmin",
      "casaos",
      "runtipi",
      "tipi",
      "esxi",
      "hypervisor",
      "vm",
      "xcpng",
      "virtualization",
      "host",
      "cosmos",
      "cosmoscloud",
    ],
  },
  {
    key: "indexer",
    label: "Indexer",
    file: "indexer.svg",
    monochrome: true,
    aliases: ["prowlarr", "jackett", "nzbhydra", "nzbhydra2", "hydra", "indexer", "torznab"],
  },

  // --- v0.2.7 new keys (Tier 2) ----------------------------------------------
  {
    key: "calendar",
    label: "Calendar",
    file: "calendar.svg",
    monochrome: true,
    aliases: [
      "radicale",
      "baikal",
      "calcom",
      "caldav",
      "calendar",
      "carddav",
      "contacts",
      "agenda",
      "events",
      "scheduling",
      "booking",
      "davx",
    ],
  },
  {
    key: "search",
    label: "Search",
    file: "search.svg",
    monochrome: true,
    aliases: [
      "searxng",
      "searx",
      "whoogle",
      "search",
      "metasearch",
      "searchengine",
      "opensearch",
      "librex",
    ],
  },
  {
    key: "requests",
    label: "Requests",
    file: "requests.svg",
    monochrome: true,
    aliases: [
      "overseerr",
      "jellyseerr",
      "ombi",
      "petio",
      "requestrr",
      "doplarr",
      "requests",
      "request",
      "watchlist",
    ],
  },
] as const;

const BY_KEY: ReadonlyMap<string, BuiltinIcon> = new Map(BUILTIN_ICONS.map((i) => [i.key, i]));

/** Look up a built-in icon by key (undefined when unknown). */
export function getBuiltinIcon(key: string): BuiltinIcon | undefined {
  return BY_KEY.get(key);
}

/** All built-in icons in registry (display) order. */
export function listBuiltinIcons(): readonly BuiltinIcon[] {
  return BUILTIN_ICONS;
}
